files:
  - source: /src/locales/en/en.yaml
    translation: /src/locales/%osx_locale%/%osx_locale%.yaml
    skip_untranslated_strings: true
preserve_hierarchy: true
project_id: '528530'
api_token_env: CROWDIN_PERSONAL_TOKEN
