name: Docker Image CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build-gpw-web:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
      IMAGE_NAME: gpw-web
    steps:
    - uses: actions/checkout@v4

    - name: 构建前端
      run: yarn install && yarn build && rm -rf ./node_modules

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/listenv/${{ env.IMAGE_NAME }}

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }} # 声明镜像源
        username: ${{ github.actor }} # 当前github 用户名
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        # Docker 构建上下文为当前目录
        context: .
        # Dockerfile 路径
        file: ./Dockerfile
        # 是否推送，默认false
        push: ${{ github.event_name != 'pull_request' }}
        # tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
        tags: ${{ env.REGISTRY }}/listenv/${{ env.IMAGE_NAME }}:latest

  build-gpw-mysql:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
      IMAGE_NAME: gpw-mysql

    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }} # 声明镜像源
        username: ${{ github.actor }} # 当前github 用户名
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        # Docker 构建上下文为当前目录
        context: ./docker/mysql/
        # Dockerfile 路径
        file: ./docker/mysql/Dockerfile
        # 是否推送，默认false
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/listenv/${{ env.IMAGE_NAME }}:latest

  build-gpw-manticore:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
      IMAGE_NAME: gpw-manticore

    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        # Docker 构建上下文为当前目录
        context: ./docker/manticore/
        # Dockerfile 路径
        file: ./docker/manticore/Dockerfile
        # 是否推送，默认false
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/listenv/${{ env.IMAGE_NAME }}:latest
